version: '3.3'

services:
  app:
    container_name: cuha-homepage
    image: openjdk:21
    volumes:
      - ./build/libs:/root
    ports:
      - "10001:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/cuha
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=cuhazngk
    command: sh -c "sleep 10; java -jar /root/homepage-0.0.1-SNAPSHOT.jar"
    restart: unless-stopped
    depends_on:
      - mysql
    networks:
      - app-network

  mysql:
    container_name: cuha-mysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: cuhazngk
      MYSQL_DATABASE: cuha
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_INITDB_SKIP_TZINFO: "yes"
      INNODB_FORCE_RECOVERY: 3  # InnoDB 복구 모드 활성화
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3308:3306"
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
